# Generated by Django 5.2 on 2025-04-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_yolo_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolo',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
